### ISSUE TITLE
Ayuda, no genera informacion el backend con base de datos

### ISSUE THREAD

**Issue by jorgeLTS** [PDNMX/SistemaDeclaraciones#1]
Hola, tengo un problema ya que cuando levanto los servicios, mi backend marca que si se conecta con la bd, pero no genera nada de información, y cuando llego a la parte de generar usuarios, no me muestra nada. el manual se sigue al pie de la letra, pero no el back no genera ni una tabla a la DB

**Comment by SolucionesDC** [comment]
> Hola, tengo un problema ya que cuando levanto los servicios, mi backend marca que si se conecta con la bd, pero no genera nada de información, y cuando llego a la parte de generar usuarios, no me muestra nada. el manual se sigue al pie de la letra, pero no el back no genera ni una tabla a la DB

Que tal jorgeLTS, tuve el mismo problema y la solución fue:
1.- Cambiar en el backend del archivo .env el localhost de la base de datos, este lo cambie por la IP local del servidor.
2.- Tuve que editar el archivo de configuración de mongo (mongod.cfg) en la propiedad "bindIp" agregue la IP local del servidor.
